version: '3.8'

services:

  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    ports:
        - 9092:9092
    environment:
        KAFKA_BROKER_ID: 0
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.56.1:9092 # bridge ip to vm container
        KAFKA_CREATE_TOPICS: "go-chat-message:2:0"   #  topic:partitions:replicas
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
        - zookeeper

  server:
    image: inno-cotravel-be
    container_name: "inno-cotravel-be"
    build: ./
    volumes:
      - inno-cotravel-be-vol:/root/
    ports:
      - 8000:8000
    environment:
      - DB_PASSWORD
      - BOT_TOKEN
    depends_on:
      - db

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.build/volumes/databases/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5432:5432

volumes:
  inno-cotravel-be-vol: