version: '3.8'

services:
  server:
    image: inno-cotravel-be
    container_name: "inno-cotravel-be"
    build: ./
    volumes:
      - inno-cotravel-be-vol:/root/
    ports:
      - 8000:8000
    environment:
      - DB_PASSWORD
    depends_on:
      - db

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.build/volumes/databases/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5432:5432

volumes:
  inno-cotravel-be-vol: