// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/protocol/message.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	FromUsername         string   `protobuf:"bytes,1,opt,name=fromUsername,proto3" json:"fromUsername,omitempty"`
	FromId               int64    `protobuf:"varint,2,opt,name=fromId,proto3" json:"fromId,omitempty"`
	ToRoomId             int64    `protobuf:"varint,3,opt,name=toRoomId,proto3" json:"toRoomId,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ContentType          int32    `protobuf:"varint,5,opt,name=contentType,proto3" json:"contentType,omitempty"`
	TransmissionType     int32    `protobuf:"varint,6,opt,name=transmissionType,proto3" json:"transmissionType,omitempty"`
	Status               int32    `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Url                  string   `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"`
	FileData             []byte   `protobuf:"bytes,9,opt,name=fileData,proto3" json:"fileData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc7b5b78212a3e3f, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetFromUsername() string {
	if m != nil {
		return m.FromUsername
	}
	return ""
}

func (m *Message) GetFromId() int64 {
	if m != nil {
		return m.FromId
	}
	return 0
}

func (m *Message) GetToRoomId() int64 {
	if m != nil {
		return m.ToRoomId
	}
	return 0
}

func (m *Message) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Message) GetContentType() int32 {
	if m != nil {
		return m.ContentType
	}
	return 0
}

func (m *Message) GetTransmissionType() int32 {
	if m != nil {
		return m.TransmissionType
	}
	return 0
}

func (m *Message) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Message) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Message) GetFileData() []byte {
	if m != nil {
		return m.FileData
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "protocol.Message")
}

func init() { proto.RegisterFile("pkg/protocol/message.proto", fileDescriptor_fc7b5b78212a3e3f) }

var fileDescriptor_fc7b5b78212a3e3f = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0xe5, 0x86, 0x26, 0xe9, 0xd1, 0xa1, 0xf2, 0x80, 0x4e, 0x9d, 0xac, 0x4e, 0x11, 0x03,
	0x1d, 0x78, 0x05, 0x16, 0x06, 0x16, 0x0b, 0x1e, 0xc0, 0x14, 0xb7, 0x8a, 0x48, 0x7c, 0x91, 0xef,
	0x3a, 0xf0, 0x14, 0xbc, 0x32, 0xca, 0x91, 0x46, 0xa0, 0x6e, 0xf7, 0x7d, 0xff, 0x2f, 0xfb, 0x74,
	0xb0, 0x1d, 0x3e, 0x4f, 0xfb, 0x21, 0x93, 0xd0, 0x81, 0xba, 0x7d, 0x1f, 0x99, 0xc3, 0x29, 0x3e,
	0xa8, 0xb0, 0xf5, 0xc5, 0xef, 0xbe, 0x17, 0x50, 0xbd, 0xfc, 0x66, 0x76, 0x07, 0xeb, 0x63, 0xa6,
	0xfe, 0x8d, 0x63, 0x4e, 0xa1, 0x8f, 0x68, 0x9c, 0x69, 0x56, 0xfe, 0x9f, 0xb3, 0x77, 0x50, 0x8e,
	0xfc, 0xfc, 0x81, 0x0b, 0x67, 0x9a, 0xc2, 0x4f, 0x64, 0xb7, 0x50, 0x0b, 0x79, 0xd2, 0xa4, 0xd0,
	0x64, 0x66, 0x8b, 0x50, 0x1d, 0x28, 0x49, 0x4c, 0x82, 0x37, 0xfa, 0xe4, 0x05, 0xad, 0x83, 0xdb,
	0x69, 0x7c, 0xfd, 0x1a, 0x22, 0x2e, 0x9d, 0x69, 0x96, 0xfe, 0xaf, 0xb2, 0xf7, 0xb0, 0x91, 0x1c,
	0x12, 0xf7, 0x2d, 0x73, 0x4b, 0x49, 0x6b, 0xa5, 0xd6, 0xae, 0xfc, 0xb8, 0x1b, 0x4b, 0x90, 0x33,
	0x63, 0xa5, 0x8d, 0x89, 0xec, 0x06, 0x8a, 0x73, 0xee, 0xb0, 0xd6, 0xbf, 0xc7, 0x71, 0xdc, 0xf6,
	0xd8, 0x76, 0xf1, 0x29, 0x48, 0xc0, 0x95, 0x33, 0xcd, 0xda, 0xcf, 0xfc, 0x5e, 0xea, 0x6d, 0x1e,
	0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x73, 0xbf, 0x35, 0x7a, 0x40, 0x01, 0x00, 0x00,
}
