port: "8000"

db:
  # host: "db"
  # port: "5432"
  
  # host: "localhost"
  # port: "5436"
  
  username: "postgres"
  dbname: "postgres"
  sslmode: "disable"

kafka:
  enabled: true
  brokers:
    - "localhost:9092"
  topic: "chat"